language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5" # 3.5 development branch
  - "3.6"
  - "3.7"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source=pypushover setup.py test
after_success:
  coveralls